auto=na.omit(read.csv("Auto.csv",na.strings="?"))
attach(auto)
fit=lm(mpg~horsepower)
summary(fit)

predict(fit, data.frame(horsepower = 98), interval = "prediction")
predict(fit, data.frame(horsepower = 95), interval = "confidence")
predict(fit, data.frame(horsepower = 95), interval = "prediction")
png("ch3_ex8_b.png")
plot(horsepower, mpg, xlab = "horsepower", ylab = "mpg", col = "black")
abline(fit, col = "red")
dev.off()

png("ch3_ex8_c.png")
par(mfrow = c(2, 2))
plot(fit)
dev.off()
png("ch3_ex9_ca.png")
pairs(auto)
dev.off()
cor(auto[-9])

fit.all = lm(mpg ~ . - name, data = auto)
summary(fit.all)
png("ch3_ex9_d.png")
par(mfrow = c(2, 2))
plot(fit.all)
dev.off()
